export const BUILDING = 'BUILDING'
export const HEIGHT = 'HEIGHT'
export const MATERIAL = 'MATERIAL'
export const SIZE_X = 'SIZE_X'
export const SIZE_Y = 'SIZE_Y'
export const RESULT = 'RESULT'
export const MESSAGE = 'MESSAGE'
export const TOTAL = 'TOTAL'